AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for the Graphene::StepFunctions::StateMachineVersion resource type

Globals:
  Function:
    Timeout: 60  # docker start-up times can be long for SAM CLI

Resources:
  TypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.amazonaws.stepfunctions.cloudformation.statemachineversion.HandlerWrapper::handleRequest
      MemorySize: 256
      Runtime: java8.al2
      CodeUri: ./target/aws-stepfunctions-statemachineversion-handler-1.0-SNAPSHOT.jar

  TestEntrypoint:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.amazonaws.stepfunctions.cloudformation.statemachineversion.HandlerWrapper::testEntrypoint
      MemorySize: 256
      Runtime: java8.al2
      CodeUri: ./target/aws-stepfunctions-statemachineversion-handler-1.0-SNAPSHOT.jar
