repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: check-case-conflict
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: mixed-line-ending
    args:
    - --fix=lf
  - id: trailing-whitespace
  - id: pretty-format-json
    args:
    - --autofix
    - --indent=2
    - --no-sort-keys
  - id: check-merge-conflict
  - id: check-yaml
    exclude: |
      (?x)^(
      codebuild-ci.yaml|
      .*dependencies\.yml$
      )$
- repo: https://github.com/aws-cloudformation/cfn-lint
  rev: v0.83.3
  hooks:
    - id: cfn-lint
      files: .*dependencies\.yml$
