Resources:
  MyExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: "states.amazonaws.com"
            Action: "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: StatesExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - iam:PassRole
                Resource: "*"
  MyStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      DefinitionString: "{\"StartAt\": \"HelloWorld\",  \"States\": {\"HelloWorld\": {\"Type\": \"Pass\", \"Result\": 1, \"End\": true}}}"
      RoleArn: !GetAtt [ MyExecutionRole, Arn ]

Outputs:
  StateMachineArn:
    Value: !Ref MyStateMachine
    Export:
      Name: !Sub awsstepfunctionsstatemachineversioncto1-${AWS::StackName}
  StateMachineRevisionId:
    Value: !GetAtt MyStateMachine.StateMachineRevisionId
    Export:
      Name: !Sub awsstepfunctionsstatemachineversioncto2-${AWS::StackName}
