AWSTemplateFormatVersion: "2010-09-09"
Description: "This template will create a simple state machine that contains one activity task state."
Resources:
  MyActivity:
    Type: "AWS::StepFunctions::Activity"
    Properties:
      Name: !Join
        - "-"
        - - "myActivityWithinStateMachine"
          - !Select
            - 2
            - !Split
              - "/"
              - !Ref "AWS::StackId"
  MyStateMachine:
    Type: "AWS::StepFunctions::StateMachine"
    Properties:
      DefinitionString:
        !Sub
          - "{\"StartAt\": \"HelloWorld\",  \"States\": {\"HelloWorld\": {\"Type\": \"Task\", \"Resource\": \"${activityArn}\", \"End\": true}}}"
          - {activityArn: !Ref MyActivity}
      RoleArn: !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:role/doesNotExist"
      Tags:
        - Key: Key1
          Value: Value1
        - Key: Key2
          Value: Value2
