AWSTemplateFormatVersion: "2010-09-09"
Description: "This template will create a simple state machine from an S3 file."
Resources:
  MyStateMachineFromJson:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      DefinitionS3Location:
        Bucket:
          Fn::ImportValue: "StepFunctionsCanaries-S3BucketName"
        Key: hello_world.json
      DefinitionSubstitutions:
        Text: HelloWorld
      RoleArn: !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:role/doesNotExist"
  MyStateMachineFromYaml:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      DefinitionS3Location:
        Bucket:
          Fn::ImportValue: "StepFunctionsCanaries-S3BucketName"
        Key: hello_world.yaml
      DefinitionSubstitutions:
        Text: HelloWorld
      RoleArn: !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:role/doesNotExist"

